version: 2

sources:
  - name: adventure_kondado_source
    description: This is a replica of the Postgres database used by our app
    tables:
      - name: person_address
        description: >
          One record per order. Includes cancelled and deleted orders.
        columns:
          - name: addressid
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: status
            description: Note that the status can change over time
